# Generated by Django 2.1.7 on 2019-03-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, verbose_name='Stock Symbol')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Open')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Close')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='High')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Low')),
                ('volume', models.IntegerField(verbose_name='Volume')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
