# Generated by Django 2.1.7 on 2019-03-10 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, verbose_name='Stock Symbol')),
                ('business', models.CharField(max_length=255, verbose_name='Business Name')),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Symbol', verbose_name='Stock Symbol'),
        ),
    ]
