'''
/**
 * Assignment 6 | ICT 4370 | Python Programming
 *
 * In this lesson, you will learn how to read and write text files in Python.
 * You will also learn how to handle exceptions, i.e. errors generated by your
 * code, to create more robust and user-friendly code.
 *
 * Use the assignment created in the previous lesson, and instead of hard
 * coding the data, populate the data using the text file available for
 * download in the assignment section in Canvas. Instead of printing the
 * report to the screen, output the report to a second text file.
 *
 * Set up your code to handle exceptions. The exceptions would include
 * inability to read from the input file or write to the output file, or
 * wrong data types - such as a string value in a location where a numerical
 * value is expected.
 *
 * @category   Assignment
 * @package    AssignmentSix
 * @author     Kyle A. Carter <kyle.carter@du.edu>
 * @copyright  2019 Kyle A. Carter
 * @license    https://opensource.org/licenses/GPL-3.0  GNU General Public License version 3
 * @version    Git: 1.0.0
 * @link       https://github.com/kylecarter/ict-4370-python-programming
 * 
 */
'''

# Run using Python 3 will not work with Python 2
import json
import os

from carterk_assignment6_owner import Owner

def process_assignment6(data, __dirname):
    '''
    Takes a JSON file loaded from a computer and outputs the data
    using the classes provided to process the data. Accepts a absolute
    system path for finding and outputing a file.
    '''
    assignment6_owners = []
    for owner in data['owners']:
        assignment6 = Owner(
            first_name=owner['first_name'],
            middle_name=owner['middle_name'],
            last_name=owner['last_name'],
            street=owner['street'],
            street_2=owner['street_2'],
            city=owner['city'],
            state=owner['state'],
            postal_code=owner['postal_code'],
            phone_number=owner['phone_number']
        )

        for stock in owner['stocks']:
            assignment6.set_stock_ownership(
                stock_name=stock['stock_name'],
                num_shares=stock['num_shares'],
                purchased=stock['purchased'],
                owner=assignment6.id,
                purchase_amount=stock['costs']['purchase_amount'],
                current_price=stock['costs']['current_price']
            )

        for bond in owner['bonds']:
            assignment6.set_bond_ownership(
                stock_name=bond['stock_name'],
                num_shares=bond['num_shares'],
                purchased=bond['purchased'],
                owner=assignment6.id,
                purchase_amount=bond['costs']['purchase_amount'],
                current_price=bond['costs']['current_price'],
                coupon=bond['coupon'],
                bond_yield=bond['bond_yield']
            )
        
        assignment6_owners.append(assignment6)

    with open(os.path.join(__dirname, 'carterk6_output.md'), 'w+') as f:
        f.write('Owner Details\n')
        f.write('=============\n')

        for person in assignment6_owners:
            owner_title = person.get_owner_full_name(
                person.first_name,
                person.middle_name,
                person.last_name
            ).title()
            f.write(owner_title + '\n')
            f.write(''.join(['-' for x in range(0, len(owner_title))]) + '\n')

            f.write('### Contact\n')
            owner_address = person.get_owner_address(
                street=person.street,
                street_2=person.street_2,
                city=person.city,
                state=person.state,
                postal_code=person.postal_code,
            )

            for x in range(0, len(owner_address)):
                f.write('* ' + owner_address[x] + '\n')

            f.write('* ' + person.get_owner_phone_num() + '\n')
            
            f.write('### Stocks\n')
            f.write(person.print_stock_details())

            f.write('### Bonds\n')
            f.write(person.print_bond_details())

# Actual program processor. The carterk6_data.json must be in the same directory
# as the carterk_assignment6.py in order for this program to work.
dirname, filename = os.path.split(os.path.abspath(__file__))
try:
    with open(os.path.join(dirname, 'carterk6_data.json')) as data:
        process_assignment6(json.load(data), dirname)
except FileNotFoundError as notfound:
    print('There is no data to process.')