# Generated by Django 2.1.7 on 2019-03-10 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_pet', models.CharField(max_length=255, verbose_name='Type of pet')),
                ('birthdate', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('breed', models.CharField(max_length=255, null=True, verbose_name='Breed')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight in Kilograms')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companions.Owner', verbose_name='Pet Owner')),
            ],
        ),
    ]
